import type { ReconstructionElement } from '../../../shared/ai/posterReconstruction';

export const FONT_STACKS: Record<ReconstructionElement['fontFamily'], string> = {
  arial: 'Arial, Helvetica, sans-serif',
  arial_black: 'Arial Black, sans-serif',
  allura: '"Allura", cursive',
  anton: '"Anton", sans-serif',
  bebas_neue: '"Bebas Neue", sans-serif',
  chewy: '"Chewy", cursive',
  courier_new: 'Courier New, Courier, monospace',
  crimson_pro: '"Crimson Pro", Georgia, serif',
  dancing_script: '"Dancing Script", cursive',
  fredoka: '"Fredoka", sans-serif',
  georgia: 'Georgia, serif',
  great_vibes: '"Great Vibes", cursive',
  impact: 'Impact, sans-serif',
  inter: '"Inter", sans-serif',
  lato: '"Lato", Arial, sans-serif',
  lilita_one: '"Lilita One", sans-serif',
  luckiest_guy: '"Luckiest Guy", cursive',
  merriweather: '"Merriweather", Georgia, serif',
  modak: '"Modak", cursive',
  montserrat: '"Montserrat", sans-serif',
  nunito: '"Nunito", Arial, sans-serif',
  open_sans: '"Open Sans", sans-serif',
  oswald: '"Oswald", sans-serif',
  pacifico: '"Pacifico", cursive',
  playfair_display: '"Playfair Display", serif',
  poppins: '"Poppins", sans-serif',
  raleway: '"Raleway", Arial, sans-serif',
  roboto: '"Roboto", sans-serif',
  sacramento: '"Sacramento", cursive',
  satisfy: '"Satisfy", cursive',
  source_sans_3: '"Source Sans 3", Arial, sans-serif',
  tangerine: '"Tangerine", cursive',
  times_new_roman: 'Times New Roman, serif',
  trebuchet_ms: '"Trebuchet MS", sans-serif',
  verdana: 'Verdana, sans-serif',
};
